### ISSUE TITLE
lua 5.3 compatibility

### ISSUE THREAD

**Issue by m7thon** [otfried/ipe#13]
Currently, ipe does not compile with lua 5.3.

However, as far as I can tell, this can be easily fixed by replacing the now deprecated `luaL_checkint` and `luaL_optlong` by `(int)luaL_checkinteger` and `(long)lueL_optinteger`. These used to be defined in this way by macros, but this is no longer so.

This makes ipe 7.1.8 compile with lua 5.3 (at least with 5.2 compatibility mode turned on), and seems to work fine.

I attach a patch file that performs these changes:

```
diff --git a/src/ipe/lfs.cpp b/src/ipe/lfs.cpp
index 2bd23fe..4f3ceaa 100644
--- a/src/ipe/lfs.cpp
+++ b/src/ipe/lfs.cpp
@@ -272,8 +272,8 @@ static int lfs_f_setmode(lua_State *L) {
 static int file_lock (lua_State *L) {
    FILE *fh = check_file (L, 1, "lock");
    const char *mode = luaL_checkstring (L, 2);
-   const long start = luaL_optlong (L, 3, 0);
-   long len = luaL_optlong (L, 4, 0);
+   const long start = (long)luaL_optinteger (L, 3, 0);
+   long len = (long)luaL_optinteger (L, 4, 0);
    if (_file_lock (L, fh, mode, start, len, "lock")) {
        lua_pushboolean (L, 1);
        return 1;
@@ -293,8 +293,8 @@ static int file_lock (lua_State *L) {
 */
 static int file_unlock (lua_State *L) {
    FILE *fh = check_file (L, 1, "unlock");
-   const long start = luaL_optlong (L, 2, 0);
-   long len = luaL_optlong (L, 3, 0);
+   const long start = (long)luaL_optinteger (L, 2, 0);
+   long len = (long)luaL_optinteger (L, 3, 0);
    if (_file_lock (L, fh, "u", start, len, "unlock")) {
        lua_pushboolean (L, 1);
        return 1;
diff --git a/src/ipe/uilua.cpp b/src/ipe/uilua.cpp
index 4d2d566..4e725cc 100644
--- a/src/ipe/uilua.cpp
+++ b/src/ipe/uilua.cpp
@@ -190,7 +190,7 @@ static int appui_setSnap(lua_State *L)
   lua_pop(L, 1);
   lua_getfield(L, -1, "gridsize");
   if (!lua_isnil(L, -1))
-    snap.iGridSize = luaL_checkint(L, -1);
+    snap.iGridSize = (int)luaL_checkinteger(L, -1);
   lua_pop(L, 1);
   lua_getfield(L, -1, "anglesize");
   if (!lua_isnil(L, -1))
@@ -198,7 +198,7 @@ static int appui_setSnap(lua_State *L)
   lua_pop(L, 1);
   lua_getfield(L, -1, "snap_distance");
   if (!lua_isnil(L, -1))
-    snap.iSnapDistance = luaL_checkint(L, -1);
+    snap.iSnapDistance = (int)luaL_checkinteger(L, -1);
   lua_pop(L, 1);
   lua_getfield(L, -1, "with_axes");
   if (!lua_isnil(L, -1))
@@ -375,7 +375,7 @@ static int shapetool_setshape(lua_State *L)
   Shape shape = check_shape(L, 1);
   int which = 0;
   if (!lua_isnoneornil(L, 2))
-    which = luaL_checkint(L, 2);
+    which = (int)luaL_checkinteger(L, 2);
   double pen = 1.0;
   if (lua_isnumber(L, 3))
     pen = luaL_checknumber(L, 3);
diff --git a/src/ipelua/ipelib.cpp b/src/ipelua/ipelib.cpp
index 9f0d7d0..39f97e3 100644
--- a/src/ipelua/ipelib.cpp
+++ b/src/ipelua/ipelib.cpp
@@ -140,7 +140,7 @@ static int document_tostring(lua_State *L)

 static int check_pageno(lua_State *L, int i, Document *d, int extra = 0)
 {
-  int n = luaL_checkint(L, i);
+  int n = (int)luaL_checkinteger(L, i);
   luaL_argcheck(L, 1 <= n && n <= d->countPages() + extra, i,
        "invalid page number");
   return n - 1;
@@ -172,7 +172,7 @@ static int document_len(lua_State *L)
 static int document_page_iterator(lua_State *L)
 {
   Document **d = check_document(L, 1);
-  int i = luaL_checkint(L, 2);
+  int i = (int)luaL_checkinteger(L, 2);
   i = i + 1;
   if (i <= (*d)->countPages()) {
     lua_pushnumber(L, i);               // new counter
diff --git a/src/ipelua/ipeluaipelet.cpp b/src/ipelua/ipeluaipelet.cpp
index 721746d..30f3b85 100644
--- a/src/ipelua/ipeluaipelet.cpp
+++ b/src/ipelua/ipeluaipelet.cpp
@@ -197,12 +197,12 @@ bool Helper::getString(const char *prompt, String &str)
 static int ipelet_run(lua_State *L)
 {
   Ipelet **p = check_ipelet(L, 1);
-  int num = luaL_checkint(L, 2) - 1;  // Lua counts starting from one
+  int num = (int)luaL_checkinteger(L, 2) - 1;  // Lua counts starting from one
   IpeletData data;
   data.iPage = check_page(L, 3)->page;
   data.iDoc = *check_document(L, 4);
-  data.iPageNo = luaL_checkint(L, 5);
-  data.iView = luaL_checkint(L, 6);
+  data.iPageNo = (int)luaL_checkinteger(L, 5);
+  data.iView = (int)luaL_checkinteger(L, 6);
   data.iLayer = check_layer(L, 7, data.iPage);
   check_allattributes(L, 8, data.iAttributes);
   // data.iSnap;
diff --git a/src/ipelua/ipeluapage.cpp b/src/ipelua/ipeluapage.cpp
index 2f03a6e..0000b3c 100644
--- a/src/ipelua/ipeluapage.cpp
+++ b/src/ipelua/ipeluapage.cpp
@@ -49,7 +49,7 @@ void ipelua::push_page(lua_State *L, Page *page, bool owned)

 static int check_objno(lua_State *L, int i, Page *p, int extra = 0)
 {
-  int n = luaL_checkint(L, i);
+  int n = (int)luaL_checkinteger(L, i);
   luaL_argcheck(L, 1 <= n && n <= p->count() + extra,
        i, "invalid object index");
   return n - 1;
@@ -65,7 +65,7 @@ int ipelua::check_layer(lua_State *L, int i, Page *p)

 int ipelua::check_viewno(lua_State *L, int i, Page *p, int extra)
 {
-  int n = luaL_checkint(L, i);
+  int n = (int)luaL_checkinteger(L, i);
   luaL_argcheck(L, 1 <= n && n <= p->countViews() + extra,
        i, "invalid view index");
   return n - 1;
@@ -151,7 +151,7 @@ static TSelect check_select(lua_State *L, int index)
 {
   TSelect w = ENotSelected;
   if (!lua_isnoneornil(L, index)) {
-    if (luaL_checkint(L, index) == 1)
+    if ((int)luaL_checkinteger(L, index) == 1)
       w = EPrimarySelected;
     else
       w = ESecondarySelected;
@@ -163,7 +163,7 @@ static TSelect check_select(lua_State *L, int index)
 static int page_object_iterator(lua_State *L)
 {
   Page *p = check_page(L, 1)->page;
-  int i = luaL_checkint(L, 2);
+  int i = (int)luaL_checkinteger(L, 2);
   i = i + 1;
   if (i <= p->count()) {
     lua_pushnumber(L, i);                            // new counter
@@ -288,7 +288,7 @@ static int page_moveLayer(lua_State *L)
 {
   Page *p = check_page(L, 1)->page;
   int index = check_layer(L, 2, p);
-  int newIndex = luaL_checkint(L, 3) - 1;
+  int newIndex = (int)luaL_checkinteger(L, 3) - 1;
   luaL_argcheck(L, 0 <= newIndex && newIndex < p->countLayers(),
        3, "invalid target index");
   p->moveLayer(index, newIndex);
diff --git a/src/ipelua/ipeluastyle.cpp b/src/ipelua/ipeluastyle.cpp
index 5dae4be..22b5a12 100644
--- a/src/ipelua/ipeluastyle.cpp
+++ b/src/ipelua/ipeluastyle.cpp
@@ -479,7 +479,7 @@ static int cascade_count(lua_State *L)
 static int cascade_sheet(lua_State *L)
 {
   Cascade *p = check_cascade(L, 1)->cascade;
-  int index = luaL_checkint(L, 2);
+  int index = (int)luaL_checkinteger(L, 2);
   luaL_argcheck(L, 1 <= index && index <= p->count(), 2, "index out of bounds");
   push_sheet(L, p->sheet(index - 1), false);
   return 1;
@@ -488,7 +488,7 @@ static int cascade_sheet(lua_State *L)
 static int cascade_insert(lua_State *L)
 {
   Cascade *p = check_cascade(L, 1)->cascade;
-  int index = luaL_checkint(L, 2);
+  int index = (int)luaL_checkinteger(L, 2);
   luaL_argcheck(L, 1 <= index && index <= p->count() + 1,
        2, "index out of bounds");
   SSheet *s = check_sheet(L, 3);
@@ -503,7 +503,7 @@ static int cascade_insert(lua_State *L)
 static int cascade_remove(lua_State *L)
 {
   Cascade *p = check_cascade(L, 1)->cascade;
-  int index = luaL_checkint(L, 2);
+  int index = (int)luaL_checkinteger(L, 2);
   luaL_argcheck(L, 1 <= index && index <= p->count(),
        2, "index out of bounds");
   p->remove(index - 1);
diff --git a/src/ipescript/lfs.cpp b/src/ipescript/lfs.cpp
index 2bd23fe..4f3ceaa 100644
--- a/src/ipescript/lfs.cpp
+++ b/src/ipescript/lfs.cpp
@@ -272,8 +272,8 @@ static int lfs_f_setmode(lua_State *L) {
 static int file_lock (lua_State *L) {
    FILE *fh = check_file (L, 1, "lock");
    const char *mode = luaL_checkstring (L, 2);
-   const long start = luaL_optlong (L, 3, 0);
-   long len = luaL_optlong (L, 4, 0);
+   const long start = (long)luaL_optinteger (L, 3, 0);
+   long len = (long)luaL_optinteger (L, 4, 0);
    if (_file_lock (L, fh, mode, start, len, "lock")) {
        lua_pushboolean (L, 1);
        return 1;
@@ -293,8 +293,8 @@ static int file_lock (lua_State *L) {
 */
 static int file_unlock (lua_State *L) {
    FILE *fh = check_file (L, 1, "unlock");
-   const long start = luaL_optlong (L, 2, 0);
-   long len = luaL_optlong (L, 3, 0);
+   const long start = (long)luaL_optinteger (L, 2, 0);
+   long len = (long)luaL_optinteger (L, 3, 0);
    if (_file_lock (L, fh, "u", start, len, "unlock")) {
        lua_pushboolean (L, 1);
        return 1;
diff --git a/src/ipeui/ipeui_common.cpp b/src/ipeui/ipeui_common.cpp
index b210083..c428e27 100644
--- a/src/ipeui/ipeui_common.cpp
+++ b/src/ipeui/ipeui_common.cpp
@@ -190,14 +190,14 @@ int Dialog::add(lua_State *L)
   luaL_checktype(L, 4, LUA_TTABLE);
   m.lua_method = LUA_NOREF;
   m.flags = 0;
-  m.row = luaL_checkint(L, 5) - 1;
-  m.col = luaL_checkint(L, 6) - 1;
+  m.row = (int)luaL_checkinteger(L, 5) - 1;
+  m.col = (int)luaL_checkinteger(L, 6) - 1;
   m.rowspan = 1;
   m.colspan = 1;
   if (!lua_isnoneornil(L, 7))
-    m.rowspan = luaL_checkint(L, 7);
+    m.rowspan = (int)luaL_checkinteger(L, 7);
   if (!lua_isnoneornil(L, 8))
-    m.colspan = luaL_checkint(L, 8);
+    m.colspan = (int)luaL_checkinteger(L, 8);
   if (m.row + m.rowspan > iNoRows)
     iNoRows = m.row + m.rowspan;
   if (m.col + m.colspan > iNoCols)
@@ -412,7 +412,7 @@ void Dialog::setUnmapped(lua_State *L, int idx)
   case EList:
   case ECombo:
     if (lua_isnumber(L, 3)) {
-      int n = luaL_checkint(L, 3);
+      int n = (int)luaL_checkinteger(L, 3);
       luaL_argcheck(L, 1 <= n && n <= int(m.items.size()), 3,
            "list index out of bounds");
       m.value = n - 1;
@@ -492,8 +492,8 @@ int Dialog::setStretch(lua_State *L)
     iRowStretch.push_back(0);

   int type = luaL_checkoption(L, 2, 0, typenames);
-  int rowcol = luaL_checkint(L, 3) - 1;
-  int stretch = luaL_checkint(L, 4);
+  int rowcol = (int)luaL_checkinteger(L, 3) - 1;
+  int stretch = (int)luaL_checkinteger(L, 4);

   if (type == 0) {
     luaL_argcheck(L, 0 <= rowcol && rowcol < iNoRows, 3,
diff --git a/src/ipeui/ipeui_gtk.cpp b/src/ipeui/ipeui_gtk.cpp
index ef9f50b..5a7a379 100644
--- a/src/ipeui/ipeui_gtk.cpp
+++ b/src/ipeui/ipeui_gtk.cpp
@@ -455,8 +455,8 @@ PMenu::~PMenu()

 int PMenu::execute(lua_State *L)
 {
-  iPopupX = luaL_checkint(L, 2);
-  iPopupY = luaL_checkint(L, 3);
+  iPopupX = (int)luaL_checkinteger(L, 2);
+  iPopupY = (int)luaL_checkinteger(L, 3);
   iSelectedItem = -1;
   gtk_menu_popup(GTK_MENU(iMenu), NULL, NULL,
         // GtkMenuPositionFunc(positionResponse), this,
@@ -697,7 +697,7 @@ static int ipeui_messageBox(lua_State *L)
     details = luaL_checkstring(L, 4);
   int buttons = 0;
   if (lua_isnumber(L, 5))
-    buttons = luaL_checkint(L, 5);
+    buttons = (int)luaL_checkinteger(L, 5);
   else if (!lua_isnoneornil(L, 5))
     buttons = luaL_checkoption(L, 5, 0, buttontype);

@@ -824,7 +824,7 @@ gboolean PTimer::elapsed()
 // does not update interval on running timer
 int PTimer::setInterval(lua_State *L)
 {
-  int t = luaL_checkint(L, 2);
+  int t = (int)luaL_checkinteger(L, 2);
   iInterval = t;
   return 0;
 }
diff --git a/src/ipeui/ipeui_qt.cpp b/src/ipeui/ipeui_qt.cpp
index 4eeaaf3..349533b 100644
--- a/src/ipeui/ipeui_qt.cpp
+++ b/src/ipeui/ipeui_qt.cpp
@@ -465,8 +465,8 @@ PMenu::~PMenu()

 int PMenu::execute(lua_State *L)
 {
-  int vx = luaL_checkint(L, 2);
-  int vy = luaL_checkint(L, 3);
+  int vx = (int)luaL_checkinteger(L, 2);
+  int vy = (int)luaL_checkinteger(L, 3);
   QAction *a = iMenu->exec(QPoint(vx, vy));
   MenuAction *ma = qobject_cast<MenuAction *>(a);
   if (ma) {
@@ -657,7 +657,7 @@ void PTimer::elapsed()

 int PTimer::setInterval(lua_State *L)
 {
-  int t = luaL_checkint(L, 2);
+  int t = (int)luaL_checkinteger(L, 2);
   iTimer->setInterval(t);
   return 0;
 }
@@ -812,7 +812,7 @@ static int ipeui_messageBox(lua_State *L)
     details = luaL_checkstring(L, 4);
   int buttons = 0;
   if (lua_isnumber(L, 5))
-    buttons = luaL_checkint(L, 5);
+    buttons = (int)luaL_checkinteger(L, 5);
   else if (!lua_isnoneornil(L, 5))
     buttons = luaL_checkoption(L, 5, 0, buttontype);

diff --git a/src/ipeui/ipeui_win.cpp b/src/ipeui/ipeui_win.cpp
index b77fe8b..533579a 100644
--- a/src/ipeui/ipeui_win.cpp
+++ b/src/ipeui/ipeui_win.cpp
@@ -683,8 +683,8 @@ PMenu::~PMenu()

 int PMenu::execute(lua_State *L)
 {
-  int vx = luaL_checkint(L, 2);
-  int vy = luaL_checkint(L, 3);
+  int vx = (int)luaL_checkinteger(L, 2);
+  int vy = (int)luaL_checkinteger(L, 3);
   int result = TrackPopupMenu(hMenu,
                  TPM_NONOTIFY | TPM_RETURNCMD | TPM_RIGHTBUTTON,
                  vx, vy, 0, hwnd, NULL);
@@ -878,7 +878,7 @@ void PTimer::elapsed()

 int PTimer::setInterval(lua_State *L)
 {
-  int t = luaL_checkint(L, 2);
+  int t = (int)luaL_checkinteger(L, 2);
   iInterval = t;
   if (iTimer)
     SetTimer(NULL, iTimer, iInterval, TimerProc);
@@ -1054,7 +1054,7 @@ static int ipeui_messageBox(lua_State *L)
     details = luaL_checkstring(L, 4);
   int buttons = 0;
   if (lua_isnumber(L, 5))
-    buttons = luaL_checkint(L, 5);
+    buttons = (int)luaL_checkinteger(L, 5);
   else if (!lua_isnoneornil(L, 5))
     buttons = luaL_checkoption(L, 5, 0, buttontype);
```

**Comment by otfried** [comment]
When I migrate to Lua 5.3, I want to go through the Ipe Lua code and clean up where integers are used and here floats are used.  I'll also need to decide where to use int and where to use lua_Integer in the C++ code.

In any case, Lua 5.3 is not yet packaged for my Linux distribution (Mint) yet, so it would be inconvenient to migrate too soon.

**Comment by m7thon** [comment]
I fully agree with what you say.

However, the above changes have no effect for lua 5.2, since lua 5.2 defines in lauxlib.h 

```
#define luaL_checkint(L,n)      ((int)luaL_checkinteger(L, (n)))
#define luaL_optlong(L,n,d)     ((long)luaL_optinteger(L, (n), (d)))
```

Therefore, this fix cannot break anything, but allows -- for the time being / unsupported / undocumented -- compilation with lua 5.3.

The reason I ask for this is that MacPorts has just updated the default lua to 5.3, breaking ipe for anyone using either the MacPorts version of ipe or compiling against the MacPorts version of lua. I wrote this as a patch for the MacPorts version of ipe, to be automatically applied by the MacPorts system, but wanted to report it here "upstream" as well. In any case, if this patch is committed in MacPorts, that version of ipe will be running with lua 5.3.

**Comment by m7thon** [comment]
Update:

Instead of modifying the code, one can simply add `-DLUA_COMPAT_5_2` to the `LUA_CFLAGS` to make ipe compile with lua 5.3. This will re-enable the above deprecated macros (among others). I am not sure if lua itself needs to be compiled with "lua 5.2 compatibility".

**Comment by jfcaron3** [comment]
Any more updates about this?  I just tried to install Ipe for the first time on my Mac, and it gives a compilation error.  I ended up finding this bug report, but I don't know how to work around it myself.

**Comment by otfried** [comment]
If you don't know how to compile yourself or how to interpret this report, why don't you simply use the precompiled Ipe bundle for Mac OS?  It's at http://github.com/otfried/ipe/raw/master/releases/7.1/ipe-7.1.8-mac.dmg

The discussion here is about MacPorts.  Are you using MacPorts?

The normal compilation instructions assume that you download the dependencies yourself, including the Lua 5.2 binaries - so this discussion should not apply.

**Comment by otfried** [comment]
I've applied the patch - it will be in the next release.
