### ISSUE TITLE
Compilation failures on OSX 10.10.5 and 10.9.5

### ISSUE THREAD

**Issue by m7thon** [otfried/ipe#60]
I am forwarding two Cocoa/Objective-C related build errors reported via MacPorts for the current Ipe 7.2.2.

1) On Yosemite 10.10.5 Xcode 7.2.1 ([Macports error report](https://trac.macports.org/ticket/50704))

```
Compiling ipeselector_cocoa.cpp...
/usr/bin/clang++ -arch x86_64 -mmacosx-version-min=10.8 -Wdeprecated-declarations -Wall -Wno-sign-conversion -g -Os -stdlib=libc++ -fPIC -DIPEUI_COCOA -std=c++11 -I../include -I../ipecairo -I/opt/local/include/cairo -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include -I/opt/local/include/pixman-1 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include -I/opt/local/include/libpng16 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include/libpng16 -I/opt/local/include  -x objective-c++ -fobjc-arc   -c -o ../../build/obj/ipecanvas/ipeselector_cocoa.o ipeselector_cocoa.cpp
ipeselector_cocoa.cpp:244:59: error: property 'frame' not found on object of type 'id'
    [[NSScrollView alloc] initWithFrame:panel.contentView.frame];
                                                          ^
1 error generated.
make[1]: *** [../../build/obj/ipecanvas/ipeselector_cocoa.o] Error 1
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_macports_trunk_dports_graphics_ipe/ipe/work/ipe-7.2.2/src/ipecanvas'
make: *** [ipecanvas] Error 2
```

I think this can (and should) be fixed easily by replacing

```
[[NSScrollView alloc] initWithFrame:panel.contentView.frame]
```

by

```
[[NSScrollView alloc] initWithFrame:[panel.contentView frame]]
```

or alternatively by casting `panel.contentView` appropriately.

2) On OSX 10.9.5 ([Macports error report](https://trac.macports.org/ticket/51110))

```
:info:build Compiling ipecanvas_cocoa.cpp...
:info:build /usr/bin/clang++ -arch x86_64 -mmacosx-version-min=10.8 -Wdeprecated-declarations -Wall -Wno-sign-conversion -g -Os -stdlib=libc++ -fPIC -DIPEUI_COCOA -std=c++11 -I../include -I../ipecairo -I/opt/local/include/cairo -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include -I/opt/local/include/pixman-1 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include/libpng16 -I/opt/local/include -x objective-c++ -fobjc-arc   -c -o ../../build/obj/ipecanvas/ipecanvas_cocoa.o ipecanvas_cocoa.cpp
:info:build ipecanvas_cocoa.cpp:48:46: error: no visible @interface for 'NSGraphicsContext' declares the selector 'CGContext'
:info:build   return [[NSGraphicsContext currentContext] CGContext];
:info:build           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~
:info:build 1 error generated.
```

I am simply forwarding this, I have not looked into what may be wrong.

**Comment by m7thon** [comment]
I should note that everything compiles fine on my own system (OSX 10.11.4, XCode 7.3), so I assume these errors are related to older versions of the Cocoa library.

**Comment by m7thon** [comment]
3) Another compilation error for OSX < 10.11 ([Macports report](https://trac.macports.org/ticket/51116))

```
Compiling ipeui_cocoa.cpp...
/usr/bin/clang++ -arch x86_64 -mmacosx-version-min=10.8 -Wdeprecated-declarations -Wall -Wno-sign-conversion -g -Os -stdlib=libc++ -fPIC -x objective-c++ -fobjc-arc  -DIPEUI_COCOA -std=c++11 -x objective-c++ -fobjc-arc  -I/opt/local/include  -c -o ../../build/obj/ipeui/ipeui_cocoa.o ipeui_cocoa.cpp
ipeui_cocoa.cpp:89:5: error: use of undeclared identifier 'NSLayoutGuide'; did you mean 'layoutGuide'?
    NSLayoutGuide *g = [[NSLayoutGuide alloc] init];
    ^~~~~~~~~~~~~
    layoutGuide
```

It seems `NSLayoutGuide` is only available on OSX 10.11 and above. Does this mean Ipe with Cocoa interface requires OSX >= 10.11? Perhaps only for compilation?

**Comment by otfried** [comment]
The compilation instructions in "macos.txt" do say:

```
Ipe runs on Mac OS 10.8 and higher, but you should compile on an
up-to-date system.
```

It's already hard enough to make sure that I build binaries that work on various versions of OSX, and to ensure that no APIs are used that are newer than the supported target version.  I did not plan on supporting compilation on arbitrary OSX versions.

Point 1. The two pieces of code:

```
[[NSScrollView alloc] initWithFrame:panel.contentView.frame]
```

and

```
[[NSScrollView alloc] initWithFrame:[panel.contentView frame]]
```

should be equivalent. I'm happy to make the change, but I don't see why changing this would fix the problem.  Apple's documentation doesn't show any change in those APIs after 10.0. Are they lying and the type of the contentView property has changed?   Are you sure that making this change fixes the problem?

Points 2. and 3. CGContext was called graphicsPort in pre 10.10 - the code detects which method exists and uses the correct one.  NSLayoutGuide only exists starting with 10.11 - the code detects this and uses an alternative implementation otherwise.  

Since I'm compiling on 10.11, I can compile calls to the newest APIs, but with older header files this fails.

There seems to be another issue in #51116, namely that NSMutableArray didn't take type parameters in 10.10.

In all these cases, the reasonable solution would be to test the OSX version and compile conditionally. E.g. on 10.9 gc_cgcontext can simply return NULL.  Also, all code pieces now marked with 

```
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
```

should simply not be compiled at all.

I don't have an older system for testing, so I cannot support compilation on old systems myself.  If you send me reasonable patches, I'd be happy to add them.

**Comment by m7thon** [comment]
Ok, I submitted a patch to Macports. I cannot test myself, either, so I suggest to wait if this resolves the compilation issues on older systems. Then I will post it here also.

Basically, I make use of the `MAC_OS_X_VERSION_MAX_ALLOWED` macro.

Note that I removed some of your `#pragma ...` lines, since I think you used them in the wrong place, i.e., disabling deprecation warnings for new API functions that are clearly not deprecated.

Finally, regarding the difference between `panel.contentView.frame` and `[panel.contentView frame]`, as I understand, the first checks at compile time if `panel.contentView` has a `frame`, while the latter does less strict type checking at compile time. In some versions of the library (10.10?), `panel.contentView` is of type `id`, so the former does not compile, while the latter does.

**Comment by otfried** [comment]
I compile with -DIPESTRICT.  This causes the inclusion of ipeosx.h, which marks all post-10.8 APIs as deprecated.  That's why I need the #pragmas on the _new_ API.   This is necessary to make sure that I build binaries that work on 10.8 upwards - unfortunately Apple's tools are no help in this respect.

As for contentView, even the 10.9 documentation claims it's of type NSView.  I guess one would have to look at the header files to figure out why this happens, but if it works this way then that's fine, too.

**Comment by m7thon** [comment]
I attach a patch to enable compilation of 7.2.2 (with Cocoa interface) on OSX 10.9 and 10.10 (testes via MacPorts build, see ticket [51116](https://trac.macports.org/ticket/51116)).

Here is an overview of the required changes:
- Create `Resources` dir in app bundle before invoking `ibtool`, since it does not create the dir on older OSX.
- Remove type specialization on `NSArray` etc. These are called "Lightweight Generics" and were introduced with XCode 7. When accessing the contents, these are then of type `id` and therefore sometimes need to be casted appropriately.
- Replace `....contentView.frame` by `[....contentView frame]`, since `contentView` apparently used to be of type `id`.
- Replace `....hidden` by `[... isHidden]` and `....visible` by `[... isVisible]`, since, erm, well, it makes it compile on OSX >= 10.9 (the getter is not called `getHidden` or `getVisible` and was apparently not found on older SDK versions).
- Conditionally compile newer API functions using the `MAC_OS_X_VERSION_MAX_ALLOWED` macro.

I can imagine that you may want to continue using the "Lightweight Generics" and for this reason choose not to support compilation on older versions of OSX. Your call.

[patch-ipe-older-osx-versions.diff.txt](https://github.com/otfried/ipe-issues/files/226661/patch-ipe-older-osx-versions.diff.txt)

**Comment by otfried** [comment]
I've applied the patches, except for taking out the generics.
