### ISSUE TITLE
Ipe crashes with errors in GSL

### ISSUE THREAD

**Issue by tinloaf** [otfried/ipe#310]
I'm running the current Ipe version (7.2.16) on Ubuntu 18.04, with `libgsl` version 2.4.

Since updating to 7.2.16, I'm experiencing some crashes, which I assume happen during the calculation of snapping points. I've built a "Minimum Non-Working Example" in which I can reproduce this. The example file can be found at:

https://cloud.iti.kit.edu/index.php/s/aSwgWJQwYXLBdkA

A video of me triggering a crash can be found here:

https://cloud.iti.kit.edu/index.php/s/ig4mwcLaJXeb4cK

Note that after drawing the line with two control points, I'm not doing anything anymore but wiggling my mouse. So, the only thing still happening should be the computation of snapping points?

The error message I get after the crash is:

```
gsl: zsolve.c:60: ERROR: leading term of polynomial must be non-zero
Default GSL error handler invoked.
[1]    14237 abort (core dumped)  ipe mnwe.ipe
```

Please let me know if I can do anything to debug this further.

**Comment by otfried** [comment]
I must have overlooked the sentence "The coefficient of the highest order term must be non-zero." in the documentation.

Fixed in 7.2.17.
