### ISSUE TITLE
ipeplatform.cpp uses inconsistent defines which breaks build: `error: 'ipeDir' was not declared in this scope`

### ISSUE THREAD

**Issue by barracuda156** [otfried/ipe#522]
`src/ipelib/ipeplatform.cpp` defines `ipeDir` only when app bundle is being built:
```
#ifdef IPEBUNDLE
String Platform::ipeDir(const char *suffix, const char *fname)
. . .
```
However then it uses `ipeDir` for Apple regardless of that:
```
#ifdef __APPLE__
    s += "\"";
    s += ipeDir("../MacOS", "ipecurl");
    s += "\" ";
. . .
```
Of course, this cannot work when app bundle is not used:
```
Compiling ipeplatform.cpp...
/opt/local/bin/g++-mp-14 -arch ppc -Wall -std=c++20 -g -Os -mmacosx-version-min=10.6 -Wdeprecated-declarations -F/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks -fPIC -DIPEUI_GTK -DGDK_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED -I../include -DIPE_GSL   -F/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks -I/opt/local/include/libpng16   -c -o ../../gtkbuild/obj/ipelib/ipeplatform.o ipeplatform.cpp
ipeplatform.cpp: In static member function 'static int ipe::Platform::runLatex(ipe::String, ipe::LatexType, ipe::String)':
ipeplatform.cpp:601:10: error: 'ipeDir' was not declared in this scope
  601 |     s += ipeDir("../MacOS", "ipecurl");
      |          ^~~~~~
make[1]: *** [../../gtkbuild/obj/ipelib/ipeplatform.o] Error 1
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_ipe/ipe/work/ipe-7.2.29/src/ipelib'
make: *** [ipelib] Error 2
```

**Comment by otfried** [comment]
The code has grown historically to be this way - compiling with `__APPLE__` but without `IPEBUNDLE` was never needed.

Feel free to make a pull request to unbundle the `IPEBUNDLE` from `__APPLE__`.   I presume you would also need changes to the make files.

May I ask why you do not want to use the Cocoa UI?

**Comment by barracuda156** [comment]
@otfried Thank you for responding.

I have seen it uses libdispatch, which means it cannot compile on 10.5. It might compile on my developer build of 10.6 ppc, but given deployment target is set to 10.10, I assumed it is unlikely. I can try, but most ppl on ppc use 10.5.8, so the problem still stands.
GTK is usually the second best after Qt4. AFAIU, Qt4 does not exist here or has been dropped.

**Comment by otfried** [comment]
I'm surprised you can compile Ipe at all on such an old platform.  I presume you are not using an old Xcode, but rather a direct installation of clang (or even gcc)?

I never had a Cocoa version that worked on pre-10.6.  and had to update to 10.7 in 2016 because I'm using some APIs that did not exist in 10.6.

Qt 4 is so old, I don't really remember what has changed since then.   I changed many signals to use lambdas, I'm not sure if Qt 4 actually supported that.

**Comment by barracuda156** [comment]
> I presume you are not using an old Xcode, but rather a direct installation of clang (or even gcc)?

@otfried Xcode gcc does not even support C++11, and here we need C++20, so yeah, this is gcc-14. Clang has been broken for ppc from its beginning and never fixed.

> I never had a Cocoa version that worked on pre-10.6.

If that was only due to `libdispatch` and not something like extensive usage of blocks, that could work for my case. Do you recall which versions was the last to support 10.6?

> and had to update to 10.7 in 2016 because I'm using some APIs that did not exist in 10.6.

Need to see what exactly. May or may not be fixable via fallbacks.

**Comment by otfried** [comment]
The first version of Ipe that had a Cocoa user interface (instead of using Qt on MacOS) was 7.2.1 from 2016/01/01.
This version set `-mmacosx-version-min=10.7`.   

I believe that choice was dictated because Ipe is using `NSLayoutConstraint` to format its UI, and those were only introduced in 10.7.  I've later upgraded the version when I was using newer APIs (although I've typically tried to load them dynamically with `respondsToSelector`).   I don't think there is a lot of those - some were related to the touchscreen function keys (I think Apple called it the touchbar, and if I understand right this is already gone again).

You could try to simply change the version to 10.6 and see what kinds of errors you get.  My guess is that everything except for ipeui and the ipe app itself should compile.

**Comment by barracuda156** [comment]
@otfried Sorry, where do I get 7.2.1 source?

**Comment by otfried** [comment]
Are you a historian?  I'm not sure why you would want to run such an ancient version - it wouldn't be able to open most Ipe files made by others - but anyway, here it is: 

[ipe-7.2.1-src.tar.gz](https://github.com/user-attachments/files/17181300/ipe-7.2.1-src.tar.gz)
